import { iJob } from "../classes/job";

export const JOBS: iJob[] = [
  {
    companyName: "Avocette",
    positionName: "Developer",
    startDate: "2020-03",
    endDate: "present",
    shortDescription: "Software customizations for municipal governments",
    longDescription:
      "Accela and Salesforce customizations. When a particular condition occurs in the government software system an automation is triggered. Customizing forms for citizen access portals.",
    bonus: [
      "Built a small library for accessing GIS data sources in Salesforce though ArcGIS REST APIs.",
      "Work with Microsoft IDEs such as Visual Studio and VS Code.",
      "Built Salesforce lightning web components to show handy information.",
      "On project teams for Seattle, Hamilton County, Regional District of Okanagan-Similkameen, and Regional Municipality of Wood Buffalo",
    ],
    software: [
      "Accela",
      "BASH",
      "GitHub",
      "IIS",
      "MS Teams",
      "Pulse Secure",
      "SQL Server Management Studio (SSMS)",
      "Salesforce",
      "VirtualBox",
      "Visual Studio Code",
      "Visual Studio",
      "Windows",
    ],
    technology: [
      "ASP.Net 4.6",
      "Accela Government Software",
      "Apex code",
      "GIS",
      "HTTP APIs",
      "JavaScript",
      "MS SQL",
      "OAuth2",
      "Postman",
      "SVN",
      "Salesforce Lightning Web Components",
      "Sharepoint",
      "Visual Studio",
      "Windows Server",
    ],
    methodology: ["RESTful API", "Remote work", "SDLC", "Various"],
  },
  {
    companyName: "Quartech",
    positionName: "Full Stack Developer on Victims Services projects",
    startDate: "2019-06",
    endDate: "2020-02",
    shortDescription:
      "Public portals to streamlining communication between the public and the Ministry of Justice to help support victims of crime.",
    longDescription: "",
    bonus: [
      "Agile methodology",
      "Angular authentication guarding, routing, and http interceptors.",
      "Assembling and bundling front end web technologies such as Angular, Bootstrap, and .NET Core for use in OpenShift.",
      "Asyncronous programming in ASP.Net Core to establish secure connections with the Microsoft Dynamics API using OAuth authentication ",
      "Building Angular forms and custom validation.",
      "Compliance with BC Gov DevHub guidelines for forms and styles.",
      "Component based application architecture.",
      "Forms to manage employee contact information",
      "Leverage existing open source projects to accelerate application development.",
      "Manually handling OpenShift DevOps tasks to deploy applications.",
      "Node versioning and dependency management.",
      "Postman API testing.",
      "Reactive forms that update calculations as the user types.",
      "Work with Microsoft IDEs such as Visual Studio and VS Code.",
    ],
    software: [
      "BASH",
      "GitHub",
      "JIRA",
      "MS Teams",
      "Microsoft Dynamics",
      "Node.js",
      "OpenShift CLI",
      "OpenShift web Console",
      "PlantUML",
      "Postman",
      "Rocket Chat",
      "Visual Studio Code",
      "Windows 10",
    ],
    technology: [
      "ASP.Net Core 2",
      "Angular 7",
      "Bootstrap",
      "HTTP APIs",
      "Microsoft Dynamics",
      "OpenShift",
    ],
    methodology: [
      "Agile",
      "Data wrangling",
      "Feature branching",
      "Kanban",
      "RESTful API",
      "Scrum",
      "UML",
    ],
  },
  {
    companyName: "Quartech",
    positionName: "Full Stack Developer",
    project: "Emergency Support Services modernization",
    startDate: "2019-03",
    endDate: "2019-02",
    shortDescription: "Digitization of emergency response system for BC.",
    longDescription: "Development to support emergency response in BC.",
    bonus: [
      "KeyCloak and SiteMinder",
      "Built and deployed an application for Community Prevention Unit front-end portal for Microsoft Dynamics Attorney General. using ASP.Net Core",
      "Express S2I landing page deployment in OpenShift.",
      "Work with EMBC for an provincial evacuee management system.",
      "Assembling front end web technologies such as Angular, Bootstrap, and .NET Core for use in OpenShift.",
      "Dependency management through Docker container development practices.",
      "Triggered DevOps pipelines in OpenShift manually to deploy production applications.",
      "Remote database administration in OpenShift using the \"oc\" command line tool paired with GUI database administration tools such as SSMS and Azure Data Studio.",
      "Leverage existing open source projects to accelerate application development.",
      "Built Angular reactive forms and custom validation.",
      "Angular authentication guarding, routing, and http interceptors.",
      "Application integration with BC Gov's SiteMinder authentication system.",
      "DevOps experience and training with OpenShift. Knowledge of systems interconnectivity in OpenShift for the EMBC Emergency Support System.",
      "User stories, comments, bugs, and task tracking in Jira. Standups and agile collaborative processes.",
      "Work with GitHub flow and code migration strategy on repos linked to OpenShift using web-hooks.",
      "Address the results of automated WAVA scans.",
      "Load testing using Websurge.",
      "Postman API testing.",
      "Use Telerik Fiddler for interception and spoofing https requests.",
      "SQLite for early-project data storage and retrieval.",
      "Installed Swagger in .Net Core for API self-documentation.",
      "Work with Microsoft IDEs.",
      "As a developer I write user stories so that I can accomplish a programming task to meet acceptance criteria.",
    ],
    software: [
      "BASH",
      "Bootstrap",
      "Docker",
      "GitHub",
      "JIRA",
      "MS Teams",
      "Node.js",
      "OpenShift CLI",
      "OpenShift web Console",
      "PlantUML",
      "Postman",
      "Puppeteer",
      "Rocket Chat",
      "Visual Studio Code",
      "Windows 10",
    ],
    technology: [
      "ASP.Net Core 2",
      "Angular 7",
      "Bootstrap",
      "HTTP APIs",
      "KeyCloak",
      "Markdown",
      "OpenShift",
      "Siteminder",
    ],
    methodology: [
      "Agile",
      "DevOps",
      "Feature branching",
      "Kanban",
      "Microservices",
      "RESTful API",
      "Scrum",
      "UML",
      "Wireframing",
    ],
  },
  {
    companyName: "Schneider Electric - Power Measurement Ltd",
    positionName: "Manufacturing Industrialization Technologist",
    startDate: "2018-04",
    endDate: "2019-04",
    shortDescription:
      "Create and maintain support tools for manufacturing and production teams.",
    longDescription:
      "Create and maintain software tools to support manufacturing and production teams.",
    bonus: [
      "Integrate machines with Active Directory (AD) and group policy.",
      "Maintenance of legacy .NET web apps running on IIS. This includes C# and VB.NET.",
      "Build web apps using Node with Angular, JavaScript, and Express.",
      "API development with Node/Express and Python/Bottle.",
      "Front-end design with Angular and Bootstrap.",
      "Email, Skype, and team meetings.",
      "Understanding of manufacturing logistics and ergonomics.",
      "Engineer new communication systems such as Raspberry Pi digital signs.",
      "Programmatic data retrieval from network drives.",
      "Denormalized database storage and retrieval with MongoDB.",
      "Normalized database querying and automation with T-SQL and SQL. (Both MS and Oracle)",
      "Use Docker for development; including dockerfile for microservice potential.",
      "Move legacy industrial systems to CentOS hypervisor (P2V).",
      "InfoSec incidence responses for Kerberos and JASBUG security vulnerabilities",
      "Configuration of CentOS and Debian Linux to meet corporate security certificates.",
      "Basic Labview understanding.",
      'Create and integrate 55" touchscreen boards for short interval meetings and digitization.',
      "Customer asset tracking automation with Python through SFTP protocol.",
      "Generate and install public/private keys on remote servers through SSH.",
      "Bash and command line experience.",
      "Sharepoint navigation changes and content management during site decommissioning.",
      "Regular full-stack reverse engineering at times when documentation is unavailable",
      "Manage user permissions on Windows Server and other admin tasks.",
      "Understand and propose ideas for changes to manufacturing systems architecture.",
      "Write tests in Python for HTTP API endpoint testing.",
      "Created and hosted wiki for manufacturing engineering.",
      "Wrote centralized step-by-step guides and documentation for various systems.",
      "Source control versioning experience in GitHub Enterprise and Perforce.",
      "IT tasks for Windows systems including OS installation, hardware troubleshooting, and office support.",
      "Electrical safety and manufacturing ergonomics design training.",
      "Create digitization solutions for manufacturing and production.",
      "Create team triage tool for automated risk assessment.",
      "Troubleshoot network and USB connected Zebra and Ricoh printers.",
      "Attended an agile development training bootcamp where I played the role of a project owner throughout the training.",
    ],
    software: [
      "ASP.Net",
      "Active Directory",
      "Angular 6",
      "BASH",
      "Bootstrap",
      "Docker",
      "Express",
      "Express",
      "GitHub Enterprise",
      "IIS web server",
      "LabView",
      "MS Access",
      "MongoDB",
      "Nmap",
      "Node.js",
      "Oracle SQL",
      "Perforce Helix",
      "PlantUML",
      "Python Flask",
      "Raspberry Pi",
      "SQL Server Management Studio (SSMS)",
      "SQL Server",
      "Sharepoint",
      "Slack",
      "VB.Net",
      "VNC",
      "VirtualBox",
      "Visual Studio Code",
      "Windows 10",
      "Windows Networking",
      "Windows Server 2016",
    ],
    technology: [
      "Microsoft Development",
      "Angular 6",
      "Bootstrap",
      "No SQL",
      "Normalized Database",
      "ERP Systems",
      "Hardware and software integrations",
      "Virtualization",
      "Documentation",
      "Markdown",
    ],
    methodology: [
      "Kanban",
      "Poka Yoke",
      "Jidoka",
      "UML",
      "APIs",
      "Process automation",
      "Logistics",
      "Industrial ergonomics",
    ],
  },
  {
    companyName: "Schneider Electric - Power Measurement Ltd",
    positionName: "Junior Software Engineer Intern",
    startDate: "2017-11",
    endDate: "2018-04",
    shortDescription:
      "Creation of software tools to support the manufacturing process.",
    longDescription: "",
    bonus: [
      "Process analysis for manufacturing change orders.",
      "Web application creation in MongoDB, Express, Angular, and NodeJS.",
      "Stakeholder presentations and public speaking.",
      "Stakeholder requirements gathering",
      "Third party software research and evaluation.",
    ],
    software: [
      "Pencil Prototyping",
      "Angular 4",
      "MongoDB",
      "Mongoose",
      "Express",
      "PlantUML",
      "Node.js",
    ],
    technology: ["Plant UML", "MEAN Stack", "Node.js"],
    methodology: [
      "Iterative development",
      "Process analysis",
      "UML",
      "Wireframing",
    ],
  },
  {
    companyName: "C3I - Capstone Project",
    positionName:
      "Stackbutton: A friendly provisioning tool for DevOps tool chains.",
    startDate: "2017",
    endDate: "2017",
    shortDescription:
      "A student project that is intended as a handy dashboard for monitoring OpenShift.",
    longDescription:
      "A student project made in Angular and Patternfly intended as a handy dashboard for monitoring OpenShift.",
    bonus: [],
    software: [
      "Angular 2",
      "Patternfly",
      "Sails",
      "Node.js",
      "Git",
      "D3",
      "C3",
      "Docker",
    ],
    methodology: [
      "Small team",
      "Feature branching",
      "Agile",
      "UML",
      "SDLC (Software Development Life Cycle)",
      "Containers",
      "Microservices",
    ],
  },
  {
    companyName: "BC Public Service Agency",
    positionName: "Application Support",
    startDate: "2015",
    endDate: "2016",
    shortDescription:
      "Six month co-op. Report creation, data analysis, implementation, process recommendations, troubleshooting, strategic threat & risk assessment (STRA), privacy impact assessment (PIA), support for data migration. Focus on mobile version.",
    longDescription:
      'Curtis joined the Time and Leave project team at the BC Public Service agency for the larger product rollout and transfer of the project to the operations team.\nThe software is based on Oracle PeopleSoft. Responsibilities included report creation, data analysis, implementation, process recommendations, troubleshooting, strategic threat & risk assessment (STRA), privacy impact assessment (PIA), and support for data migration.\n With oversight from project managers, he developed project management  and documentation skills through a sub-project called "Mobile Enablement". The project was taken from charter to completion and is built on GreyHeller\'s People Mobile software. The project can be seen by visiting the BC Gov’s MyHR portal from a mobile device. This was a tremendous learning experience and introduction to the software development life cycle in large organizations.',
    bonus: [],
    software: [
      "Oracle PeopleSoft",
      "Sharepoint",
      "Microsoft Excel",
      "Greyheller People Mobile",
    ],
    methodology: [
      "PIA (Privacy Impact Assessment)",
      "STRA (Strategic Threat and Risk assessment)",
      "SDLC (Software Development Life Cycle)",
      "QA (Quality assurance)",
    ],
  },
  {
    companyName: "LayCraft Design",
    positionName: "Founder, Graphic Designer, Client Management",
    startDate: "2007",
    endDate: "2014",
    shortDescription:
      "Client communication, administration, creative direction, print design, illustration, photography, branding consultation, and contract instruction.",
    longDescription:
      "Established in 2007, LayCraft Design was a full-service creative company. Curtis' primary responsibilities included client communication, administration, creative direction, web design, print design, illustration, photography, branding consultation, and contract instruction.\nExamples of clients: Government of Alberta computer training centre, Sun Media Group, BC Art Teachers Association, The Red Cross, The Salvation Army, and Events Edmonton. Created various branding, ads, promotions for nightclubs, restaurants, industrial companies, and other businesses.",
    bonus: [],
  },
  {
    companyName: "Interactivity Board Game Café",
    positionName: "Game Lord",
    startDate: "2013",
    endDate: "2016",
    shortDescription: "Teaching board games. Café duties. Technical stuff.",
    longDescription:
      "Curtis taught games and sold games at the board games café. Curtis has taught and played over 400 modern designer board games. During the startup phase, he was responsible for a miscellany of work: setting up POS, TouchBistro server, and counting and arranging inventory. Board games are a beautiful mixture of algorithms, graphic design, game theory, and cardboard.",
    bonus: [],
  },
  {
    companyName: "The Salvation Army Community and Family Services",
    positionName: "Communication Designer",
    startDate: "2011",
    endDate: "2012",
    shortDescription:
      "Website content, rebranding, communication design, computer literacy instruction.",
    longDescription:
      "Curtis set up and the new Joomla website. He collected and wrote descriptions about the many programs and services that The Salvation Army Stan Hagen Centre for Families provides. He redesigned print materials to fit the centre's renaming: forms, business cards, certificates, manuals, signs, and etc… Curtis taught computer literacy skills in the computer lab: Windows, File Management, Word, Excel, and PowerPoint. During Christmas he was responsible for various organizational tasks surrounding the Christmas Hamper and Toy Shop programs such as collecting and managing client intake data.",
    bonus: [],
  },
  {
    companyName: "Northern Alberta Institute of Technology (NAIT)",
    positionName: "Instructor",
    startDate: "2007",
    endDate: "2009",
    shortDescription:
      "Curriculum development, and instruction for graphic design classes.",
    longDescription:
      "Curtis developed curriculum and instructed at The Northern Alberta Institute of Technology (NAIT).  Classes included InDesign Level 1 & 2, Acrobat Level 1 & 2, Print Tools for Scanning & Printing, Photoshop Level 1-3, Digital Photo Basic, and Design Theory. He was also an instructor for NAIT's kids summer camps in GameMaker, digital photography, and Photoshop.",
    bonus: [],
  },
  {
    companyName: "Edmonton Digital Arts College",
    positionName: "Instructor",
    startDate: "2007",
    endDate: "2009",
    shortDescription: "Instructor for graphic design tools. Focused training.",
    longDescription:
      "After graduation, the college hired Curtis for his ability to instruct. Curtis' work was mainly in corporate-training and focused-training. He provided classes for various organizations such as: Blackberry & Acrobat Pro training for the Government of Alberta, InDesign Training for Sun Media Group, Adobe creative suite training for the University of Alberta's faculty of extension.",
    bonus: [],
  },
  {
    companyName: "AT&T (Via: Convergys)",
    positionName: "Customer Service Representative",
    startDate: "2006",
    endDate: "2006",
    shortDescription:
      "Tech-support, after-hours tech-support, billing support, activations and transfers.",
    longDescription:
      "Customers across the western USA called for troubleshooting and support with their GSM devices. Curtis used Siebel and AXIS CRM systems to track, resolve, and notate issues. Included troubleshooting of various GSM issues using AT&T tools.",
    bonus: [],
  },
  {
    companyName: "Starbucks Coffee Co.",
    positionName: "Barista",
    startDate: "2004",
    endDate: "2006",
    shortDescription: "Slinging coffee and schmoozing with patrons.",
    longDescription:
      "Curtis' responsibility at Starbucks was primarily a Barista but included training other staff on making bar drinks. He started in West Edmonton Mall Chapters and transferred to Callingwood. He then moved to Terra Losa. Starbucks' work flexibility allowed him to work in dozens of stores in Edmonton and with many types of people.",
    bonus: [],
  },
];
